// Generated by Own.TypedBuilder from Order.cs. Do not edit: change Order.cs and regenerate.
//
// The state protocol of Order: one [ProtocolToken] per state, one transition per
// [Transition], one [ProtocolRegion] per state with a way out, the checked refinement,
// the strict storage of the state, and the staged builder. Own.NET analyses this file as
// source: it is the protocol's trusted definition surface.

using System;

namespace OrderBackend.Domain;

partial class Order
{
    // Draft -> Submit -> Submitted
    internal void ApplySubmit(DateTime at)
    {
        OnSubmit(at);
        Status = OrderStatus.Submitted;
    }

    // Submitted -> Approve -> Approved
    internal void ApplyApprove(DateTime at)
    {
        OnApprove(at);
        Status = OrderStatus.Approved;
    }

    // Approved -> Ship -> Shipped
    internal void ApplyShip(DateTime at, int trackingNumber)
    {
        OnShip(at, trackingNumber);
        Status = OrderStatus.Shipped;
    }

    /// Starts a new Order in its initial state, Draft. Build() exists only once every
    /// required field was given.
    public static DraftBuilder.CustomerStep Create() => new();

    public sealed class DraftBuilder
    {
        private readonly string _customer;

        private DraftBuilder(string customer)
        {
            _customer = customer;
        }

        public Order Build() => new() { Customer = _customer, Status = OrderStatus.Draft };

        public sealed class CustomerStep
        {
            internal CustomerStep()
            {
            }

            public DraftBuilder Customer(string customer)
            {
                ArgumentNullException.ThrowIfNull(customer);
                return new DraftBuilder(customer);
            }
        }
    }
}

/// The runtime half of the refinement: the state came from data, so it is checked once,
/// at the region entry.
public sealed class InvalidOrderStateException(int id, OrderStatus actual, OrderStatus required)
    : InvalidOperationException($"order {id} is {actual}, not {required}")
{
    public int Id { get; } = id;

    public OrderStatus Actual { get; } = actual;

    public OrderStatus Required { get; } = required;
}

/// A persisted state that is not exactly one of OrderStatus's names. Never mapped to a
/// state: no default, no case folding, no number.
public sealed class CorruptOrderStateException(string raw)
    : InvalidOperationException($"the persisted order state '{raw}' is not an OrderStatus")
{
    public string Raw { get; } = raw;
}

/// The one mapping between OrderStatus and its stored text: the exact member name.
public static class OrderStatusStorage
{
    public static string ToStore(OrderStatus state) => state switch
    {
        OrderStatus.Draft => "Draft",
        OrderStatus.Submitted => "Submitted",
        OrderStatus.Approved => "Approved",
        OrderStatus.Shipped => "Shipped",
        _ => throw new CorruptOrderStateException(state.ToString()),
    };

    public static OrderStatus FromStore(string raw) =>
        TryFromStore(raw, out var state) ? state : throw new CorruptOrderStateException(raw);

    public static bool TryFromStore(string? raw, out OrderStatus state)
    {
        switch (raw)
        {
            case "Draft":
                state = OrderStatus.Draft;
                return true;
            case "Submitted":
                state = OrderStatus.Submitted;
                return true;
            case "Approved":
                state = OrderStatus.Approved;
                return true;
            case "Shipped":
                state = OrderStatus.Shipped;
                return true;
            default:
                state = default;
                return false;
        }
    }
}

/// Order in state Draft. A transition spends this token and hands back the next one.
[ProtocolToken]
public readonly ref struct DraftOrder
{
    private readonly Order _order;

    internal DraftOrder(Order order) => _order = order;

    public int Id => _order.Id;

    public SubmittedOrder Submit(DateTime at)
    {
        _order.ApplySubmit(at);
        return new SubmittedOrder(_order);
    }
}

/// Order in state Submitted. A transition spends this token and hands back the next one.
[ProtocolToken]
public readonly ref struct SubmittedOrder
{
    private readonly Order _order;

    internal SubmittedOrder(Order order) => _order = order;

    public int Id => _order.Id;

    public ApprovedOrder Approve(DateTime at)
    {
        _order.ApplyApprove(at);
        return new ApprovedOrder(_order);
    }
}

/// Order in state Approved. A transition spends this token and hands back the next one.
[ProtocolToken]
public readonly ref struct ApprovedOrder
{
    private readonly Order _order;

    internal ApprovedOrder(Order order) => _order = order;

    public int Id => _order.Id;

    public ShippedOrder Ship(DateTime at, int trackingNumber)
    {
        _order.ApplyShip(at, trackingNumber);
        return new ShippedOrder(_order);
    }
}

/// Order in state Shipped. Terminal: no transition leaves it.
[ProtocolToken]
public readonly ref struct ShippedOrder
{
    private readonly Order _order;

    internal ShippedOrder(Order order) => _order = order;

    public int Id => _order.Id;
}

public delegate void DraftRegion(DraftOrder draft);
public delegate void SubmittedRegion(SubmittedOrder submitted);
public delegate void ApprovedRegion(ApprovedOrder approved);

/// The checked refinement: an Order whose state is only known at run time becomes a token
/// inside the callback, or the call throws and no token exists. A state no transition
/// leaves has no region: its token could never be spent.
public static class OrderProtocol
{
    [ProtocolRegion]
    public static void WithDraft(Order order, DraftRegion body)
    {
        ArgumentNullException.ThrowIfNull(order);
        ArgumentNullException.ThrowIfNull(body);
        if (order.Status != OrderStatus.Draft)
            throw new InvalidOrderStateException(order.Id, order.Status, OrderStatus.Draft);
        body(new DraftOrder(order));
    }

    [ProtocolRegion]
    public static void WithSubmitted(Order order, SubmittedRegion body)
    {
        ArgumentNullException.ThrowIfNull(order);
        ArgumentNullException.ThrowIfNull(body);
        if (order.Status != OrderStatus.Submitted)
            throw new InvalidOrderStateException(order.Id, order.Status, OrderStatus.Submitted);
        body(new SubmittedOrder(order));
    }

    [ProtocolRegion]
    public static void WithApproved(Order order, ApprovedRegion body)
    {
        ArgumentNullException.ThrowIfNull(order);
        ArgumentNullException.ThrowIfNull(body);
        if (order.Status != OrderStatus.Approved)
            throw new InvalidOrderStateException(order.Id, order.Status, OrderStatus.Approved);
        body(new ApprovedOrder(order));
    }
}
