#!/usr/bin/env python3
"""Generated differential mini-program battery (P-022 step 4, issue #214).

A *deterministic* generator of small OwnLang programs built from the ownership
primitives — acquire / release / use / move / call(borrow|consume) / branch /
loop / return — plus the Python `(line, code)` goldens for each. Persisted to
`tests/fixtures/diag_diff_gen.json`; the Rust side
(`rust/crates/own-analysis/tests/diff_gen.rs`) replays every case through the
ported `check` surface with **zero Python** and, on any divergence, prints the
seed + source so it can become a permanent regression fixture.

Determinism: each program is built from `random.Random(seed)` for `seed in
range(COUNT)`, so regeneration is byte-stable. Declarations are emitted only at
statement-list top level (never inside a branch/loop body) so every reference is
in scope — the generator exercises *ownership* faults (leak / use-after-release /
double-release / use-after-move / borrow-vs-consume), not resolver name errors.

Run:  python tests/test_diff_gen_fixtures.py            (verify)
      python tests/test_diff_gen_fixtures.py --write    (regenerate)
      python tests/run_tests.py                         (runs it as part of the suite)
"""

from __future__ import annotations

import json
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ownlang.__main__ import _collect

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "diag_diff_gen.json")

# Number of seeded programs. Bounded so the fixture stays reviewable; each seed is
# an independent deterministic program.
COUNT = 160

_PRELUDE = (
    "module M\n"
    "resource R { acquire open release close }\n"
    "extern fn Use(borrow R);\n"
    "extern fn Take(consume R);\n"
)


def _gen_source(rng: random.Random) -> str:
    counter = [0]
    live: list[str] = []  # names declared so far (owned handles), always in scope

    def new_var() -> str:
        counter[0] += 1
        return f"v{counter[0]}"

    def block(depth: int, n_stmts: int) -> list[str]:
        out: list[str] = []
        for _ in range(n_stmts):
            out.extend(stmt(depth))
        return out

    def stmt(depth: int) -> list[str]:
        # Declarations only at top level so references never go out of scope.
        top = depth == 0
        ops = ["use", "release", "move", "call", "branch", "loop"]
        if top:
            ops = ["acquire", "acquire", *ops]  # bias toward introducing resources
        op = rng.choice(ops)

        if op == "acquire" and top:
            v = new_var()
            live.append(v)
            return [f"let {v} = acquire R(1);"]
        if op in ("use", "release", "move", "call") and not live:
            return []
        if op == "use":
            return [f"use {rng.choice(live)};"]
        if op == "release":
            return [f"release {rng.choice(live)};"]
        if op == "move" and top:
            src = rng.choice(live)
            v = new_var()
            live.append(v)
            return [f"let {v} = move {src};"]
        if op == "call":
            v = rng.choice(live)
            fn = rng.choice(["Use", "Take"])
            return [f"{fn}({v});"]
        if op == "branch" and depth < 2:
            inner = block(depth + 1, rng.randint(1, 3))
            return ["if (n) {", *[f"    {ln}" for ln in inner], "}"]
        if op == "loop" and depth < 2:
            inner = block(depth + 1, rng.randint(1, 3))
            return ["while (n) {", *[f"    {ln}" for ln in inner], "}"]
        return []

    body = block(0, rng.randint(3, 9))
    body.append("return;")
    indented = "\n".join(f"    {ln}" for ln in body)
    return f"{_PRELUDE}fn gen(n: int) {{\n{indented}\n}}\n"


def build() -> dict[str, object]:
    cases: list[dict[str, object]] = []
    for seed in range(COUNT):
        rng = random.Random(seed)
        source = _gen_source(rng)
        diags, _ = _collect(source)
        cases.append(
            {"seed": seed, "source": source, "diags": [[d.line, d.code] for d in diags]}
        )
    return {
        "comment": (
            "GENERATED by tests/test_diff_gen_fixtures.py --write; do not edit. "
            "Deterministic seeded ownership mini-programs; Python (ownlang) is "
            "authoritative, rust/crates/own-analysis/tests/diff_gen.rs replays "
            "each and prints seed+source on divergence (issue #214)."
        ),
        "cases": cases,
    }


def _render(data: dict[str, object]) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def run() -> int:
    expected = _render(build())
    if not os.path.exists(FIXTURE):
        print(f"FAIL: {FIXTURE} missing; regenerate with "
              f"'python tests/test_diff_gen_fixtures.py --write'")
        return 1
    with open(FIXTURE, encoding="utf-8") as f:
        actual = f.read()
    if actual != expected:
        print(f"FAIL: {FIXTURE} is stale (generator or checker changed); "
              f"regenerate with 'python tests/test_diff_gen_fixtures.py --write' "
              f"and re-run the Rust side (cd rust && cargo test)")
        return 1
    data = json.loads(actual)
    cases = data["cases"]
    n_find = sum(len(c["diags"]) for c in cases)
    print(f"generated differential fixtures OK: {len(cases)} seeded programs, "
          f"{n_find} total (line, code) pairs, verified in sync")
    return 0


if __name__ == "__main__":
    if "--write" in sys.argv[1:]:
        os.makedirs(os.path.dirname(FIXTURE), exist_ok=True)
        with open(FIXTURE, "w", encoding="utf-8") as f:
            f.write(_render(build()))
        print(f"wrote {FIXTURE}")
        raise SystemExit(0)
    raise SystemExit(run())
