#!/usr/bin/env python3
"""The #259 checkpoint-1 ledger, interpreted once (the fourth census).

`tests/fixtures/ownir_validation.json` is the frozen BR-D1 acceptance language:
every control, the verdict the reference gives it, and — on a rejection — the
category the ledger claims for the MECHANISM that produced it. Three numbers
about it have been typed into status surfaces so far (`216 controls`,
`matrix 35/181`, `48 mutations`), and typed numbers are how a status table
drifts from the tree it describes. This module is the one reader, so the
census a document shows is computed from the ledger rather than remembered.

Pure: no `ownlang` import and no side effects, like `verdict_census.py` and
`coordinate_census.py` beside it. It does NOT run the door — the ledger is
already the reference's recorded answer, regenerated by
`python tests/test_ownir_validation_fixtures.py --write`, and re-deriving it
here would be a second oracle with a second opinion.

What it counts, and why each split is the one that matters:

* **by section** — the ledger's own grouping, which is BR-D1's check order.
  A section with acceptances and no rejections is a door nobody probed; one
  with rejections and no acceptance twin is a rejection nothing discriminates.
* **by category** — the seven-category taxonomy on two axes. `shape` versus
  `location` is the split #326's census had to discover, and this change moved
  a family across it, so the two counts are the ones a reader compares.
* **the coordinate family on its own** — every control whose document carries
  a `line` or a `column`, because that is the family #259's final acceptance
  moved and the one a reviewer needs to find without reading 294 records.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass

HERE = os.path.dirname(os.path.abspath(__file__))
LEDGER = os.path.join(HERE, "fixtures", "ownir_validation.json")
SCHEMA_VERSION = 1
ACCEPTED = "accepted"


@dataclass(frozen=True)
class SectionRow:
    section: str
    accepted: int
    rejected: int
    by_category: tuple[tuple[str, int], ...]


@dataclass(frozen=True)
class ValidationCensus:
    schema_version: int
    controls: int
    accepted: int
    rejected: int
    categories: tuple[tuple[str, str], ...]
    by_category: tuple[tuple[str, int], ...]
    sections: tuple[SectionRow, ...]
    coordinate_controls: int
    coordinate_accepted: int
    coordinate_by_category: tuple[tuple[str, int], ...]


class ValidationCensusError(Exception):
    def __init__(self, problems: list[str]) -> None:
        super().__init__("; ".join(problems))
        self.problems = problems


def _carries_coordinate(node: object) -> bool:
    """Does this control's document carry a `line`, `ctor_line` or `column`
    anywhere? Structural, at any depth, so a control nested inside a function
    body counts exactly like one at the top level."""
    if isinstance(node, dict):
        if {"line", "ctor_line", "column"} & node.keys():
            return True
        return any(_carries_coordinate(v) for v in node.values())
    if isinstance(node, list):
        return any(_carries_coordinate(v) for v in node)
    return False


def compute_validation_census() -> ValidationCensus:
    problems: list[str] = []
    try:
        with open(LEDGER, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, ValueError) as e:
        raise ValidationCensusError([f"ledger unreadable: {e}"]) from e
    if data.get("schema_version") != SCHEMA_VERSION:
        problems.append(
            f"ledger schema_version {data.get('schema_version')!r} != {SCHEMA_VERSION} — "
            f"a reviewed contract, not a passing reshape")
    cases = data.get("cases")
    if not isinstance(cases, list) or not cases:
        raise ValidationCensusError([*problems, "ledger 'cases' must be a non-empty array"])
    declared = data.get("categories")
    if not isinstance(declared, dict):
        raise ValidationCensusError([*problems, "ledger 'categories' must be an object"])

    by_category: dict[str, int] = {}
    per_section: dict[str, dict[str, int]] = {}
    accepted = rejected = 0
    coord = coord_accepted = 0
    coord_by_category: dict[str, int] = {}
    for i, case in enumerate(cases):
        if not isinstance(case, dict):
            problems.append(f"cases[{i}] is not an object")
            continue
        name = case.get("name", f"cases[{i}]")
        section = case.get("section")
        verdict = case.get("verdict")
        category = case.get("category")
        if not isinstance(section, str) or not section:
            problems.append(f"{name}: 'section' must be a non-empty string")
            continue
        if verdict == "accept":
            if category is not None:
                problems.append(f"{name}: accepted, but carries a category")
            key = ACCEPTED
            accepted += 1
        elif verdict == "reject":
            if not isinstance(category, str) or category not in declared:
                problems.append(f"{name}: rejected with category {category!r}, "
                                f"which the ledger does not declare")
                continue
            key = category
            rejected += 1
        else:
            problems.append(f"{name}: verdict {verdict!r} is neither accept nor reject")
            continue
        by_category[key] = by_category.get(key, 0) + 1
        section_counts = per_section.setdefault(section, {})
        section_counts[key] = section_counts.get(key, 0) + 1
        if _carries_coordinate(case.get("document")) and not case.get("raw"):
            coord += 1
            coord_by_category[key] = coord_by_category.get(key, 0) + 1
            if key == ACCEPTED:
                coord_accepted += 1
    if problems:
        raise ValidationCensusError(problems)

    sections = tuple(
        SectionRow(
            section=section,
            accepted=counts.get(ACCEPTED, 0),
            rejected=sum(n for k, n in counts.items() if k != ACCEPTED),
            by_category=tuple(sorted((k, n) for k, n in counts.items() if k != ACCEPTED)),
        )
        for section, counts in sorted(per_section.items())
    )
    return ValidationCensus(
        schema_version=SCHEMA_VERSION,
        controls=accepted + rejected,
        accepted=accepted,
        rejected=rejected,
        categories=tuple(sorted((k, str(v)) for k, v in declared.items())),
        by_category=tuple(sorted(by_category.items())),
        sections=sections,
        coordinate_controls=coord,
        coordinate_accepted=coord_accepted,
        coordinate_by_category=tuple(sorted(coord_by_category.items())),
    )
