// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: the inner call receives the handle through a reference upcast (captured there, unwrapped); the outer call receives the inner result (nested_call_result)
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_nested_transparent_inner
{
    static Stream Wrap(Stream s) { return s; }
    static void Use(Stream s) { }
    static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); Use(Wrap((Stream)r)); keep.Dispose(); }
}
