// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: a direct flow into a non-consuming callee and nothing else tracked; the legacy pass reads the pass as an escape, the fact rides in the orphan carrier
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_orphan_direct
{
    static void Same(MemoryStream m) { }
    static void M() { var r = new MemoryStream(); Same(r); }
}
