// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: parentheses around a handle whose parameter type needs op_Implicit; the conversion wins over the transparent-looking syntax (§10.6.3)
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_parens_user_implicit
{
    sealed class Box { public static implicit operator Box(MemoryStream m) { return new Box(); } }
    static void TakeBox(Box b) { }
    static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); TakeBox((r)); keep.Dispose(); }
}
