// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: a named, reordered argument carrying a reference upcast; the declared ordinal is the parameter's, the fact is the unwrapped var
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_named_transparent
{
    static void Sink(Stream s, bool leaveOpen) { }
    static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); Sink(leaveOpen: true, s: (Stream)r); keep.Dispose(); }
}
