// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: one arm of a conditional is an explicit user-defined cast of the handle, the other arm is not a handle; the cast arm is excluded inside the may-value form
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_mayvalue_arm_user_cast
{
    sealed class XBox { public static explicit operator XBox(MemoryStream m) { return new XBox(); } }
    static void TakeXBox(XBox b) { }
    static void M(bool flag) { var r = new MemoryStream(); var other = new XBox(); var keep = new MemoryStream(); TakeXBox(flag ? (XBox)r : other); keep.Dispose(); }
}
