// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: a conditional whose whole value passes through op_Implicit at the parameter; an arm that reaches the callee only through a user-defined conversion is not a handle alternative (registry conversion_rules)
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_mayvalue_arm_user_conversion
{
    sealed class Box { public static implicit operator Box(MemoryStream m) { return new Box(); } }
    static void TakeBox(Box b) { }
    static void M(bool flag) { var r = new MemoryStream(); var q = new MemoryStream(); var keep = new MemoryStream(); TakeBox(flag ? r : q); keep.Dispose(); }
}
