// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: parentheses around an explicit user-defined cast; the hidden call inside the cast expression is the edge that decides
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_parens_user_explicit
{
    sealed class XBox { public static explicit operator XBox(MemoryStream m) { return new XBox(); } }
    static void TakeXBox(XBox b) { }
    static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); TakeXBox(((XBox)r)); keep.Dispose(); }
}
