// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: a constructor whose parameter is a params array, expanded form; one opaque slot at the params ordinal, the call relevant, call_kind object_creation
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_ctor_params
{
    sealed class SinkP2 { public SinkP2(params Stream[] xs) { } }
    static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); new SinkP2(r); keep.Dispose(); }
}
