// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: a delegate invocation with named, reordered arguments; the delegate's declared parameter names resolve the binding, callee stays null
using System;
using System.IO;
using System.Collections.Generic;

static class H_comp_delegate_named
{
    delegate void Take(Stream s, bool leaveOpen);
    static void M(Take take) { var r = new MemoryStream(); var keep = new MemoryStream(); take(leaveOpen: true, s: r); keep.Dispose(); }
}
