// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// call-like site: a nested call inside a constructor initializer's argument; the inner call captures the handle, the initializer receives its result (nested_call_result)
using System;
using System.IO;
using System.Collections.Generic;

static class H_ctorinit_nested_call
{
    static Stream Wrap(Stream s) { return s; }
    class Base { public Base(Stream s, bool b) { } }
    sealed class Holder : Base { public Holder(MemoryStream r) : base(Wrap(r), true) { } }
}
