// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// call-like site: a constructor initializer with named, reordered arguments and a reference upcast on the handle; the target constructor's declared ordinals bind
using System;
using System.IO;
using System.Collections.Generic;

static class H_ctorinit_named_transparent
{
    class Base { public Base(Stream s, bool b) { } }
    sealed class Holder : Base { public Holder(MemoryStream r) : base(b: true, s: (Stream)r) { } }
}
