// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// site form: a struct handle as the receiver of an extension method on object; the receiver conversion is boxing, so nothing of the handle reaches ordinal 0
using System;
using System.IO;
using System.Collections.Generic;

static class H_ext_boxed_receiver
{
    struct Token : IDisposable { public void Dispose() { } }
    static void ExtObj(this object o, bool leaveOpen) { }
    static void M(Token r) { r.ExtObj(true); }
}
