// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// site form: a reduced extension method invoked through `?.` on the handle; the receiver still binds declared ordinal 0 (F-CONDITIONAL-RECEIVER, repaired in A2.2-4R3)
using System;
using System.IO;
using System.Collections.Generic;

static class H_ext_conditional_access
{
    static void Ext(this Stream s, bool leaveOpen) { }
    static void M() { MemoryStream? r = new MemoryStream(); var keep = new MemoryStream(); r?.Ext(true); keep.Dispose(); }
}
