// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// member kind: a method of a record struct; neither a class declaration nor a record class (finding F-MEMBER)
using System;
using System.IO;
using System.Collections.Generic;

static class H_member_record_struct
{
    static void Sink(Stream s, bool leaveOpen) { }
    record struct Holder(int X) { public void M(MemoryStream r) { Sink(r, true); } }
}
