// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// member kind: a property setter passing its `value` parameter; accessors are not BaseMethodDeclarationSyntax and are never visited (finding F-MEMBER)
using System;
using System.IO;
using System.Collections.Generic;

static class H_member_accessor
{
    static void Sink(Stream s, bool leaveOpen) { }
    static MemoryStream Slot { set { Sink(value, true); } }
}
