// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// member kind: the call sits in a declared local function; the capture is a named non-call context of the method and the inner call is the known unobserved gap, counted, not RED
using System;
using System.IO;
using System.Collections.Generic;

static class H_member_local_function
{
    static void Sink(Stream s, bool leaveOpen) { }
    static void M() { var r = new MemoryStream(); void L() { Sink(r, true); } L(); }
}
