// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// member kind: an expression-bodied method with an owned parameter; the legacy pass visits block bodies only, so neither carrier sees the call (finding F-MEMBER)
using System;
using System.IO;
using System.Collections.Generic;

static class H_member_expression_bodied
{
    static void Sink(Stream s, bool leaveOpen) { }
    static void M(MemoryStream r) => Sink(r, true);
}
