// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// member kind: a default interface method with a body; the legacy pass enumerates class declarations only, and the root cause is the enumeration, not struct-ness (finding F-MEMBER)
using System;
using System.IO;
using System.Collections.Generic;

static class H_member_default_interface_method
{
    static void Sink(Stream s, bool leaveOpen) { }
    interface IHolder { void M(MemoryStream r) { Sink(r, true); } }
}
