// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=as_may_fail binding=params carrier=unmodelled_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_as_may_fail_params_unmodelled_param
{
    sealed class SinkP2 { public SinkP2(params MemoryStream?[] xs) { } }
    static readonly object Gate = new object();
    static void M(Stream r)
    {
        lock (Gate) { new SinkP2(r as MemoryStream); }
    }
}
