// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=user_implicit binding=named carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_user_implicit_named_orphan_local
{
    sealed class Sink2 { public Sink2(Box s, bool leaveOpen) { } }
    sealed class Box { public static implicit operator Box(MemoryStream m) { return new Box(); } }
    static object Field;
    static void M()
    {
        var r = new MemoryStream();
        new Sink2(leaveOpen: true, s: r);
        Field = r;
    }
}
