// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=parens binding=default carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_parens_default_orphan_local
{
    sealed class SinkD2 { public SinkD2(Stream s, bool leaveOpen = true) { } }
    static object Field;
    static void M()
    {
        var r = new MemoryStream();
        new SinkD2((r));
        Field = r;
    }
}
