// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=bang binding=pos carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_bang_pos_record_param
{
    sealed class Sink2 { public Sink2(Stream s, bool leaveOpen) { } }
    static void M(MemoryStream r)
    {
        new Sink2(r!, true);
    }
}
