// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=user_explicit binding=params carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_user_explicit_params_orphan_local
{
    sealed class SinkP2 { public SinkP2(params XBox[] xs) { } }
    sealed class XBox { public static explicit operator XBox(MemoryStream m) { return new XBox(); } }
    static object Field;
    static void M()
    {
        var r = new MemoryStream();
        new SinkP2((XBox)r);
        Field = r;
    }
}
