// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=none binding=refout carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_none_refout_record_local
{
    sealed class SinkRef2 { public SinkRef2(ref MemoryStream s) { } }
    static void M()
    {
        var r = new MemoryStream();
        var keep = new MemoryStream();
        new SinkRef2(ref r);
        keep.Dispose();
    }
}
