// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=as_upcast binding=params carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_as_upcast_params_record_param
{
    sealed class SinkP2 { public SinkP2(params Stream[] xs) { } }
    static void M(MemoryStream r)
    {
        new SinkP2(r as Stream);
    }
}
