// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=collection binding=params carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_collection_params_orphan_local
{
    sealed class SinkP2 { public SinkP2(params List<Stream>[] xs) { } }
    static object Field;
    static void M()
    {
        var r = new MemoryStream();
        new SinkP2(new List<Stream> { r });
        Field = r;
    }
}
