// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=switch binding=params carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_switch_params_orphan_local
{
    sealed class SinkP2 { public SinkP2(params Stream[] xs) { } }
    static object Field;
    static void M(int k)
    {
        var r = new MemoryStream();
        var q = new MemoryStream();
        new SinkP2(k switch { 0 => r, _ => q });
        Field = r;
        Field = q;
    }
}
