// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=cast_identity binding=named carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_cast_identity_named_record_local
{
    sealed class Sink2 { public Sink2(Stream s, bool leaveOpen) { } }
    static void M()
    {
        var r = new MemoryStream();
        var keep = new MemoryStream();
        new Sink2(leaveOpen: true, s: (MemoryStream)r);
        keep.Dispose();
    }
}
