// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ctor value_flow=none binding=params carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ctor_none_params_unmodelled_local
{
    sealed class SinkP2 { public SinkP2(params Stream[] xs) { } }
    static readonly object Gate = new object();
    static void M()
    {
        var r = new MemoryStream();
        lock (Gate) { new SinkP2(r); }
    }
}
