// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=parens binding=params carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_parens_params_record_local
{
    delegate void TakeP(params Stream[] xs);
    static void M(TakeP takeP)
    {
        var r = new MemoryStream();
        var keep = new MemoryStream();
        takeP((r));
        keep.Dispose();
    }
}
