// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=boxing binding=default carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_boxing_default_unmodelled_local
{
    delegate void TakeD(object s, bool leaveOpen = true);
    struct Token : IDisposable { public void Dispose() { } }
    static readonly object Gate = new object();
    static void M(TakeD takeD)
    {
        var r = new Token();
        lock (Gate) { takeD(r); }
    }
}
