// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=bang binding=named carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_bang_named_unmodelled_local
{
    delegate void Take(Stream s, bool leaveOpen);
    static readonly object Gate = new object();
    static void M(Take take)
    {
        var r = new MemoryStream();
        lock (Gate) { take(leaveOpen: true, s: r!); }
    }
}
