// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=nested binding=default carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_nested_default_unmodelled_local
{
    delegate void TakeD(Stream s, bool leaveOpen = true);
    static Stream Wrap(Stream s) { return s; }
    static readonly object Gate = new object();
    static void M(TakeD takeD)
    {
        var r = new MemoryStream();
        lock (Gate) { takeD(Wrap(r)); }
    }
}
