// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=closure binding=default carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_closure_default_unmodelled_local
{
    delegate void TakeD(Action s, bool leaveOpen = true);
    static void Use(Stream s) { }
    static readonly object Gate = new object();
    static void M(TakeD takeD)
    {
        var r = new MemoryStream();
        lock (Gate) { takeD(() => Use(r)); }
    }
}
