// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=cast_checked binding=params carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_cast_checked_params_orphan_local
{
    delegate void TakeP(params Stream[] xs);
    static object Field;
    static void M(TakeP takeP)
    {
        Stream r = new MemoryStream();
        takeP((MemoryStream)r);
        Field = r;
    }
}
