// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=cast_identity binding=pos carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_cast_identity_pos_orphan_local
{
    delegate void Take(Stream s, bool leaveOpen);
    static object Field;
    static void M(Take take)
    {
        var r = new MemoryStream();
        take((MemoryStream)r, true);
        Field = r;
    }
}
