// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=cast_upcast binding=default carrier=unmodelled_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_cast_upcast_default_unmodelled_param
{
    delegate void TakeD(Stream s, bool leaveOpen = true);
    static readonly object Gate = new object();
    static void M(MemoryStream r, TakeD takeD)
    {
        lock (Gate) { takeD((Stream)r); }
    }
}
