// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=as_may_fail binding=default carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_as_may_fail_default_orphan_local
{
    delegate void TakeD(MemoryStream? s, bool leaveOpen = true);
    static object Field;
    static void M(TakeD takeD)
    {
        Stream r = new MemoryStream();
        takeD(r as MemoryStream);
        Field = r;
    }
}
