// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=switch binding=default carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_switch_default_unmodelled_local
{
    delegate void TakeD(Stream s, bool leaveOpen = true);
    static readonly object Gate = new object();
    static void M(int k, TakeD takeD)
    {
        var r = new MemoryStream();
        var q = new MemoryStream();
        lock (Gate) { takeD(k switch { 0 => r, _ => q }); }
    }
}
