// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=none binding=refout carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_none_refout_record_param
{
    delegate void TakeRef(ref MemoryStream s);
    static void M(MemoryStream r, TakeRef takeRef)
    {
        takeRef(ref r);
    }
}
