// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=user_implicit binding=default carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_user_implicit_default_unmodelled_local
{
    delegate void TakeD(Box s, bool leaveOpen = true);
    sealed class Box { public static implicit operator Box(MemoryStream m) { return new Box(); } }
    static readonly object Gate = new object();
    static void M(TakeD takeD)
    {
        var r = new MemoryStream();
        lock (Gate) { takeD(r); }
    }
}
