// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=del value_flow=tuple binding=default carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_del_tuple_default_unmodelled_local
{
    delegate void TakeD((Stream s, int n) s, bool leaveOpen = true);
    static readonly object Gate = new object();
    static void M(TakeD takeD)
    {
        var r = new MemoryStream();
        lock (Gate) { takeD((r, 1)); }
    }
}
