// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=tuple binding=named carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_tuple_named_record_param
{
    static void Ext(this (Stream s, int n) s, bool leaveOpen) { }
    static void M(MemoryStream r)
    {
        ((r, 1)).Ext(leaveOpen: true);
    }
}
