// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=bang binding=default carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_bang_default_record_local
{
    static void ExtD(this Stream s, bool leaveOpen = true) { }
    static void M()
    {
        var r = new MemoryStream();
        var keep = new MemoryStream();
        r!.ExtD();
        keep.Dispose();
    }
}
