// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=cast_checked binding=named carrier=unmodelled_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_cast_checked_named_unmodelled_param
{
    static void Ext(this Stream s, bool leaveOpen) { }
    static readonly object Gate = new object();
    static void M(Stream r)
    {
        lock (Gate) { ((MemoryStream)r).Ext(leaveOpen: true); }
    }
}
