// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=user_explicit binding=named carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_user_explicit_named_record_param
{
    static void Ext(this XBox s, bool leaveOpen) { }
    sealed class XBox { public static explicit operator XBox(MemoryStream m) { return new XBox(); } }
    static void M(MemoryStream r)
    {
        ((XBox)r).Ext(leaveOpen: true);
    }
}
