// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=as_upcast binding=named carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_as_upcast_named_record_local
{
    static void Ext(this Stream s, bool leaveOpen) { }
    static void M()
    {
        var r = new MemoryStream();
        var keep = new MemoryStream();
        (r as Stream).Ext(leaveOpen: true);
        keep.Dispose();
    }
}
