// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=method_group binding=params carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_method_group_params_record_param
{
    static void ExtP(this Stream s, params Action[] xs) { }
    static void M(MemoryStream r)
    {
        Stream.Null.ExtP(r.Dispose);
    }
}
