// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=none binding=named carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_none_named_orphan_local
{
    static void Ext(this Stream s, bool leaveOpen) { }
    static object Field;
    static void M()
    {
        var r = new MemoryStream();
        r.Ext(leaveOpen: true);
        Field = r;
    }
}
