// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=user_implicit binding=params carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_user_implicit_params_record_param
{
    static void ExtP(this Stream s, params Box[] xs) { }
    sealed class Box { public static implicit operator Box(MemoryStream m) { return new Box(); } }
    static void M(MemoryStream r)
    {
        Stream.Null.ExtP(r);
    }
}
