// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=collection binding=named carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_collection_named_record_param
{
    static void Ext(this List<Stream> s, bool leaveOpen) { }
    static void M(MemoryStream r)
    {
        new List<Stream> { r }.Ext(leaveOpen: true);
    }
}
