// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=parens binding=pos carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_parens_pos_unmodelled_local
{
    static void Ext(this Stream s, bool leaveOpen) { }
    static readonly object Gate = new object();
    static void M()
    {
        var r = new MemoryStream();
        lock (Gate) { (r).Ext(true); }
    }
}
