// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=boxing binding=named carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_boxing_named_record_param
{
    static void Ext(this object s, bool leaveOpen) { }
    struct Token : IDisposable { public void Dispose() { } }
    static void M(Token r)
    {
        r.Ext(leaveOpen: true);
    }
}
