// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=ext value_flow=cast_identity binding=params carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_ext_cast_identity_params_record_param
{
    static void ExtP(this Stream s, params Stream[] xs) { }
    static void M(MemoryStream r)
    {
        Stream.Null.ExtP((MemoryStream)r);
    }
}
