// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=user_implicit binding=pos carrier=unmodelled_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_user_implicit_pos_unmodelled_param
{
    static void Sink(Box s, bool leaveOpen) { }
    sealed class Box { public static implicit operator Box(MemoryStream m) { return new Box(); } }
    static readonly object Gate = new object();
    static void M(MemoryStream r)
    {
        lock (Gate) { Sink(r, true); }
    }
}
