// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=cast_checked binding=default carrier=record_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_cast_checked_default_record_param
{
    static void SinkD(Stream s, bool leaveOpen = true) { }
    static void M(Stream r)
    {
        SinkD((MemoryStream)r);
    }
}
