// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=none binding=default carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_none_default_record_local
{
    static void SinkD(Stream s, bool leaveOpen = true) { }
    static void M()
    {
        var r = new MemoryStream();
        var keep = new MemoryStream();
        SinkD(r);
        keep.Dispose();
    }
}
