// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=cast_identity binding=default carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_cast_identity_default_unmodelled_local
{
    static void SinkD(Stream s, bool leaveOpen = true) { }
    static readonly object Gate = new object();
    static void M()
    {
        var r = new MemoryStream();
        lock (Gate) { SinkD((MemoryStream)r); }
    }
}
