// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=boxing binding=pos carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_boxing_pos_record_local
{
    static void Sink(object s, bool leaveOpen) { }
    struct Token : IDisposable { public void Dispose() { } }
    static void M()
    {
        var r = new Token();
        var keep = new MemoryStream();
        Sink(r, true);
        keep.Dispose();
    }
}
