// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=bang binding=params carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_bang_params_orphan_local
{
    static void SinkP(params Stream[] xs) { }
    static object Field;
    static void M()
    {
        var r = new MemoryStream();
        SinkP(r!);
        Field = r;
    }
}
