// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=parens binding=pos carrier=unmodelled_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_parens_pos_unmodelled_param
{
    static void Sink(Stream s, bool leaveOpen) { }
    static readonly object Gate = new object();
    static void M(MemoryStream r)
    {
        lock (Gate) { Sink((r), true); }
    }
}
