// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=boxing binding=pos carrier=unmodelled_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_boxing_pos_unmodelled_param
{
    static void Sink(object s, bool leaveOpen) { }
    struct Token : IDisposable { public void Dispose() { } }
    static readonly object Gate = new object();
    static void M(Token r)
    {
        lock (Gate) { Sink(r, true); }
    }
}
