// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=closure binding=pos carrier=unmodelled_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_closure_pos_unmodelled_param
{
    static void Sink(Action s, bool leaveOpen) { }
    static void Use(Stream s) { }
    static readonly object Gate = new object();
    static void M(MemoryStream r)
    {
        lock (Gate) { Sink(() => Use(r), true); }
    }
}
