// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=none binding=refout carrier=orphan_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_none_refout_orphan_local
{
    static void SinkRef(ref MemoryStream s) { }
    static object Field;
    static void M()
    {
        var r = new MemoryStream();
        SinkRef(ref r);
        Field = r;
    }
}
