// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=user_explicit binding=pos carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_user_explicit_pos_record_local
{
    static void Sink(XBox s, bool leaveOpen) { }
    sealed class XBox { public static explicit operator XBox(MemoryStream m) { return new XBox(); } }
    static void M()
    {
        var r = new MemoryStream();
        var keep = new MemoryStream();
        Sink((XBox)r, true);
        keep.Dispose();
    }
}
