// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=as_may_fail binding=pos carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_as_may_fail_pos_record_local
{
    static void Sink(MemoryStream? s, bool leaveOpen) { }
    static void M()
    {
        Stream r = new MemoryStream();
        var keep = new MemoryStream();
        Sink(r as MemoryStream, true);
        keep.Dispose();
    }
}
