// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=collection binding=pos carrier=record_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_collection_pos_record_local
{
    static void Sink(List<Stream> s, bool leaveOpen) { }
    static void M()
    {
        var r = new MemoryStream();
        var keep = new MemoryStream();
        Sink(new List<Stream> { r }, true);
        keep.Dispose();
    }
}
