// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=as_upcast binding=pos carrier=unmodelled_local
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_as_upcast_pos_unmodelled_local
{
    static void Sink(Stream s, bool leaveOpen) { }
    static readonly object Gate = new object();
    static void M()
    {
        var r = new MemoryStream();
        lock (Gate) { Sink(r as Stream, true); }
    }
}
