// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// composition: site=inv value_flow=user_explicit binding=pos carrier=unmodelled_param
using System;
using System.IO;
using System.Collections.Generic;

static class H_pw_inv_user_explicit_pos_unmodelled_param
{
    static void Sink(XBox s, bool leaveOpen) { }
    sealed class XBox { public static explicit operator XBox(MemoryStream m) { return new XBox(); } }
    static readonly object Gate = new object();
    static void M(MemoryStream r)
    {
        lock (Gate) { Sink((XBox)r, true); }
    }
}
