// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// shadowing witness: the non-candidate `r` comes first, the candidate second; order must not matter to a symbol-bound reading (F-SHADOW, repaired in A2.2-4R1)
using System;
using System.IO;
using System.Collections.Generic;

static class H_shadow_sibling_scopes_reversed
{
    static void Sink(Stream s, bool leaveOpen) { }
    static void M() { { Stream r = Stream.Null; Sink(r, true); } { var r = new MemoryStream(); Sink(r, true); } }
}
