// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// shadowing witness (the GO's literal form): `Stream r = ...; { Stream r2 = ...; Sink(r2); }`; the non-candidate r2 is captured by nobody and the candidate r is captured by symbol
using System;
using System.IO;
using System.Collections.Generic;

static class H_shadow_owner_form
{
    static void Sink(Stream s, bool leaveOpen) { }
    static void M() { Stream r = new MemoryStream(); { Stream r2 = Stream.Null; Sink(r2, true); } Sink(r, true); }
}
