// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// shadowing witness: two locals spelled `r` in sibling scopes; only the first is a candidate. A handle set keyed by spelling captured the second call too (F-SHADOW, repaired in A2.2-4R1: the sidecar binds by symbol)
using System;
using System.IO;
using System.Collections.Generic;

static class H_shadow_sibling_scopes
{
    static void Sink(Stream s, bool leaveOpen) { }
    static void M() { { var r = new MemoryStream(); Sink(r, true); } { Stream r = Stream.Null; Sink(r, true); } }
}
