// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// shadowing witness: a handle created inside a lambda shares its spelling with a string local of the method; the string is not a candidate of anything (finding F-SHADOW)
using System;
using System.IO;
using System.Collections.Generic;

static class H_shadow_lambda_local
{
    static void Run(Action a) { a(); }
    static void Use4(string s) { }
    static void M() { Run(() => { var r = new MemoryStream(); r.Dispose(); }); { string r = "x"; Use4(r); } }
}
