// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// vocabulary edge: the handle is the index of an element access (finding F-VOCAB)
using System;
using System.IO;
using System.Collections.Generic;

static class H_vocab_indexer_argument
{
    static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); var d = new Dictionary<Stream, int>(); d[r] = 1; keep.Dispose(); }
}
