// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// call-like site: an owned constructor parameter forwarded through `: base(...)`, a really invoked constructor's declared ordinal 0 (ruled a fact shape in A2.2-4R4, landed in A2.2-4R5: call_kind constructor_initializer)
using System;
using System.IO;
using System.Collections.Generic;

static class H_vocab_constructor_initializer
{
    class Base { public Base(MemoryStream r, bool b) { } }
    sealed class Holder : Base { public Holder(MemoryStream r) : base(r, true) { } }
}
