// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// vocabulary edge: the handle is an interpolation hole and the string is the argument; the A2.2-4R4 ruling names it interpolation_hole
using System;
using System.IO;
using System.Collections.Generic;

static class H_vocab_interpolation_hole
{
    static void Log(string s) { }
    static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); Log($"{r}"); keep.Dispose(); }
}
