// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// vocabulary edge: the handle is compared and the boolean is the argument; the A2.2-4R4 ruling names it predicate_result
using System;
using System.IO;
using System.Collections.Generic;

static class H_vocab_tested_operand
{
    static void Log(bool b) { }
    static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); Log(r != null); keep.Dispose(); }
}
