// GENERATED by scripts/p037_hostile_census.py (P-037 A2.2-4 hostile census); do not edit.
// vocabulary edge: an owned constructor parameter forwarded through `: base(...)`, a really invoked constructor's declared ordinal 0; ruled a call-like fact shape in A2.2-4R4, landing in A2.2-4R5 (finding F-CTOR-INIT)
using System;
using System.IO;
using System.Collections.Generic;

static class H_vocab_constructor_initializer
{
    class Base { public Base(MemoryStream r, bool b) { } }
    sealed class Holder : Base { public Holder(MemoryStream r) : base(r, true) { } }
}
