//! Prints `theories/RustTables.v`: the P-037 kernel's finite operations as
//! full truth tables, plus solver vectors, computed by the kernel crate
//! itself (`formal/p037-kernel`, linked by path).
//!
//! `Correspondence.v` proves the Rocq model equal to these tables on the
//! whole finite domain and re-runs the Rocq solvers on the vectors. If the
//! Rust kernel changes, regenerating this file makes `Correspondence.v` fail
//! instead of letting the two semantics drift.
//!
//! Usage (from `formal/mathcomp-spike`):
//!   cargo run -q --manifest-path export/Cargo.toml > theories/RustTables.v

use p037_kernel::{
    apply, contribute, lower, read, solve, solve_with, Cells, Coord, Edge, Lattice, Lowered, Mask,
    Selection, Shape, System, Transfer, Transform, MAX_COORDS, MAX_EDGES,
};

const _: () = assert!(MAX_COORDS == 3, "the vector format below spells out 3 slots");

fn t(x: Transfer) -> &'static str {
    match x {
        Transfer::Bot => "Bot",
        Transfer::No => "No",
        Transfer::Must => "Must",
        Transfer::May => "May",
        Transfer::Unknown => "Unknown",
    }
}

fn c(x: Cells) -> String {
    format!("({}, {})", t(x.pos), t(x.neg))
}

fn tf(x: Transform) -> &'static str {
    match x {
        Transform::ConstPos => "ConstPos",
        Transform::ConstNeg => "ConstNeg",
        Transform::Id => "Id",
        Transform::Neg => "Neg",
        Transform::Opaque => "Opaque",
    }
}

fn m(x: Mask) -> &'static str {
    match x {
        Mask::Both => "Both",
        Mask::PosOnly => "PosOnly",
        Mask::NegOnly => "NegOnly",
    }
}

fn sel(x: Selection) -> &'static str {
    match x {
        Selection::Pos => "SelPos",
        Selection::Neg => "SelNeg",
        Selection::Unselected => "Unselected",
    }
}

fn low(x: Lowered) -> &'static str {
    match x {
        Lowered::Consume => "Consume",
        Lowered::Borrow => "Borrow",
        Lowered::Plain => "Plain",
    }
}

fn all_cells() -> Vec<Cells> {
    let mut v = Vec::new();
    for &pos in &Transfer::ALL {
        for &neg in &Transfer::ALL {
            v.push(Cells { pos, neg });
        }
    }
    v
}

fn list(name: &str, ty: &str, rows: &[String]) {
    println!("Definition {name} : seq ({ty}) := [::");
    for (k, r) in rows.iter().enumerate() {
        let sep = if k + 1 == rows.len() { "" } else { ";" };
        println!("  {r}{sep}");
    }
    println!("].\n");
}

/// xorshift64, seeded: the vectors are part of the checked-in evidence.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

fn random_system(rng: &mut Rng) -> System {
    loop {
        let n = 1 + rng.below(MAX_COORDS);
        let dead = Coord {
            shape: Shape::Uncond,
            seed: Cells::BOT,
            edges: [None; MAX_EDGES],
        };
        let mut coords = [dead; MAX_COORDS];
        for co in coords.iter_mut().take(n) {
            let split = rng.below(2) == 0;
            let a = Transfer::ALL[rng.below(5)];
            let b = Transfer::ALL[rng.below(5)];
            co.shape = if split { Shape::Split(0) } else { Shape::Uncond };
            co.seed = if split { Cells { pos: a, neg: b } } else { Cells::diag(a) };
            for slot in co.edges.iter_mut() {
                if rng.below(3) != 0 {
                    *slot = Some(Edge {
                        callee: rng.below(n),
                        transform: Transform::ALL[rng.below(5)],
                        mask: Mask::ALL[rng.below(3)],
                    });
                }
            }
        }
        let sys = System { n, coords };
        if sys.well_formed() {
            return sys;
        }
    }
}

fn main() {
    println!("(* GENERATED by formal/mathcomp-spike/export from formal/p037-kernel.");
    println!("   Do not edit: regenerate with");
    println!("   cargo run -q --manifest-path export/Cargo.toml > theories/RustTables.v *)");
    println!("From mathcomp Require Import boot.");
    println!("From P037Spike Require Import P037.\n");
    println!("Definition vector :=");
    println!("  (seq cells * seq (seq (nat * transform * mask)) * seq (seq cells) * seq (seq cells))%type.\n");

    println!("Definition rust_transfer_height := {}.", <Transfer as Lattice>::HEIGHT);
    println!("Definition rust_cells_height := {}.", <Cells as Lattice>::HEIGHT);
    println!("Definition rust_max_coords := {MAX_COORDS}.");
    println!(
        "Definition rust_max_passes_cells := {}.\n",
        p037_kernel::max_passes(<Cells as Lattice>::HEIGHT)
    );

    let mut rows = Vec::new();
    for &a in &Transfer::ALL {
        for &b in &Transfer::ALL {
            rows.push(format!("({}, {}, {})", t(a), t(b), t(a.join(b))));
        }
    }
    list("rust_join", "transfer * transfer * transfer", &rows);

    let rows: Vec<String> = Transfer::ALL
        .iter()
        .map(|&a| format!("({}, {}, {})", t(a), t(a.fin()), low(lower(a))))
        .collect();
    list("rust_fin_lower", "transfer * transfer * lowered", &rows);

    let rows: Vec<String> = all_cells()
        .into_iter()
        .map(|x| format!("({}, {})", c(x), t(x.collapse())))
        .collect();
    list("rust_collapse", "cells * transfer", &rows);

    let mut rows = Vec::new();
    for &tr in &Transform::ALL {
        for &mk in &Mask::ALL {
            for x in all_cells() {
                rows.push(format!(
                    "({}, {}, {}, {})",
                    tf(tr),
                    m(mk),
                    c(x),
                    c(contribute(mk, read(tr, x)))
                ));
            }
        }
    }
    list("rust_contribute_read", "transform * mask * cells * cells", &rows);

    let mut rows = Vec::new();
    for x in all_cells() {
        for &s in &Selection::ALL {
            // the guard index of a split is irrelevant to application: pin it
            let split: Vec<Lowered> = (0..3).map(|g| apply(Shape::Split(g), x, s)).collect();
            assert!(split.windows(2).all(|w| w[0] == w[1]), "apply depends on the guard index");
            rows.push(format!("(Split, {}, {}, {})", c(x), sel(s), low(split[0])));
            rows.push(format!("(Uncond, {}, {}, {})", c(x), sel(s), low(apply(Shape::Uncond, x, s))));
        }
    }
    list("rust_apply", "shape * cells * selection * lowered", &rows);

    // Solver vectors: (seeds, edges, Jacobi chain of `sys`, Jacobi chain of
    // `sys.collapsed()`), over MAX_COORDS slots (dead slots are ⊥ with no
    // edges, which is what `step` computes for them). Each chain is produced
    // by the kernel's own `System::step` from ⊥ to its fixpoint and must end
    // at `solve`; the chaotic solver under a random fair schedule must agree.
    let mut rng = Rng(0x5eed_0037_c0c0_a117);
    let mut rows = Vec::new();
    let chain = |sys: &System| -> Vec<[Cells; MAX_COORDS]> {
        let mut x = [Cells::BOT; MAX_COORDS];
        let mut out = Vec::new();
        loop {
            let next = [sys.step(0, &x), sys.step(1, &x), sys.step(2, &x)];
            if next == x {
                return out;
            }
            out.push(next);
            x = next;
        }
    };
    let show = |x: &[Cells; MAX_COORDS]| {
        format!("[:: {}]", x.iter().map(|&v| c(v)).collect::<Vec<_>>().join("; "))
    };
    let show_chain = |ch: &[[Cells; MAX_COORDS]]| {
        format!("[:: {}]", ch.iter().map(show).collect::<Vec<_>>().join("; "))
    };
    for _ in 0..300 {
        let sys = random_system(&mut rng);
        let mut sched: Vec<usize> = (0..sys.n).collect();
        for _ in 0..rng.below(4) {
            sched.push(rng.below(sys.n));
        }
        for k in (1..sched.len()).rev() {
            sched.swap(k, rng.below(k + 1));
        }
        let (Some(j), Some(ch), Some(col)) =
            (solve(&sys), solve_with(&sys, &sched), solve(&sys.collapsed()))
        else {
            panic!("solver did not stabilize: {sys:?}");
        };
        assert_eq!(j, ch, "chaotic != Jacobi: {sys:?} {sched:?}");
        let (cj, cc) = (chain(&sys), chain(&sys.collapsed()));
        assert_eq!(cj.last().copied().unwrap_or([Cells::BOT; MAX_COORDS]), j);
        assert_eq!(cc.last().copied().unwrap_or([Cells::BOT; MAX_COORDS]), col);
        let seeds: Vec<String> = (0..MAX_COORDS)
            .map(|i| if i < sys.n { c(sys.coords[i].seed) } else { c(Cells::BOT) })
            .collect();
        let edges: Vec<String> = (0..MAX_COORDS)
            .map(|i| {
                let es: Vec<String> = if i < sys.n {
                    sys.coords[i]
                        .edges
                        .iter()
                        .flatten()
                        .map(|e| format!("({}, {}, {})", e.callee, tf(e.transform), m(e.mask)))
                        .collect()
                } else {
                    Vec::new()
                };
                format!("[:: {}]", es.join("; "))
            })
            .collect();
        rows.push(format!(
            "([:: {}], [:: {}], {}, {})",
            seeds.join("; "),
            edges.join("; "),
            show_chain(&cj),
            show_chain(&cc)
        ));
    }
    list("rust_vectors", "vector", &rows);
}
