<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><AssemblyName>Lib</AssemblyName><RootNamespace>Lib</RootNamespace><AssemblyVersion>1.0.0.0</AssemblyVersion><FileVersion>1.0.0.0</FileVersion><InformationalVersion>B-cached-1.0.1</InformationalVersion><Nullable>enable</Nullable><Deterministic>true</Deterministic></PropertyGroup></Project>
