#!/usr/bin/env python3
"""P-037 A2.2-4: the generated hostile census for the completeness oracle.

corpus/p037-hostile/cases/<case>.cs is one self-contained program per case and
corpus/p037-hostile/expected.json is the DESIGNED classification of every case:
which universe occurrence of the case's method must be captured (site kind,
declared ordinal, representation) or excluded (by which of the eleven frozen
names), which carrier production must deliver the record in, and, for a case
that witnesses a classified finding, exactly which RED the oracle must raise.
The design is written by this generator from the frozen taxonomy
(corpus/p037-relevance/registry.json, docs/notes/p037-formal-kernel.md §10.6),
never recorded from a run: the oracle is checked against it, so the oracle and
production cannot agree on nonsense.

Four factors are covered pairwise (every value of one factor meets every value
of every other at least once, under the feasibility constraints C# imposes):

  site form         inv (static invocation), ext (reduced extension receiver),
                    ctor (object creation), del (delegate invocation)
  value-flow        the 21 argument shapes of the relevance probe: the bare
                    handle, the transparent wrappers, the may-value forms, the
                    conversions, and every named exclusion's shape
  binding mode      positional, named and reordered, an expanded params slot,
                    ref, an omitted optional argument
  carrier admission the legacy pass's admission: a functions[] record through a
                    tracked local or an owned parameter, the guarded_functions[]
                    orphan carrier through an escaped local, and the unmodelled
                    construct gate (lock) for either handle kind

plus the named compositions the A2.2-4 GO asked for, the shadowing witnesses
(same spelling, different symbol), the member kinds the legacy pass does not
visit, and the argument shapes the frozen vocabulary has no name for.

Usage:
  p037_hostile_census.py generate      # (re)write the cases and expected.json
  p037_hostile_census.py check         # drift: the committed files equal a regeneration
"""

from __future__ import annotations

import argparse
import itertools
import json
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "corpus" / "p037-hostile"
CASES = OUT / "cases"
EXPECTED = OUT / "expected.json"
SCHEMA = "p037-hostile-census/1"
HEADER = ("// GENERATED by scripts/p037_hostile_census.py "
          "(P-037 A2.2-4 hostile census); do not edit.")
BOX = ("sealed class Box { public static implicit operator Box(MemoryStream m) "
       "{ return new Box(); } }")
XBOX = ("sealed class XBox { public static explicit operator XBox(MemoryStream m) "
        "{ return new XBox(); } }")

SITES = ["inv", "ext", "ctor", "del"]
WRAPPERS = ["none", "parens", "bang", "cast_identity", "cast_upcast", "as_upcast", "cast_checked",
            "as_may_fail", "cond", "coalesce", "switch", "user_implicit", "user_explicit", "boxing",
            "nested", "tuple", "array", "collection", "closure", "method_group", "nameof", "member"]
BINDINGS = ["pos", "named", "params", "refout", "default"]
CARRIERS = ["record_local", "record_param", "orphan_local", "unmodelled_local", "unmodelled_param"]

# What reaches the callee, per value-flow shape: the frozen class and, for an indirect
# shape, the one named exclusion.
EXCLUSION = {
    "user_implicit": "user_conversion", "user_explicit": "user_conversion",
    "boxing": "boxing_conversion", "tuple": "tuple_construction",
    "array": "container_construction", "collection": "container_construction",
    "closure": "closure_capture", "method_group": "method_group_conversion",
    "nameof": "nameof_operand", "member": "member_access_on_handle",
}
MAY_VALUE = {"cond", "coalesce", "switch", "as_may_fail"}
# The callee's parameter type for the handle's slot, per shape.
PARAM_TYPE = {
    "as_may_fail": "MemoryStream?", "user_implicit": "Box", "user_explicit": "XBox",
    "boxing": "object", "tuple": "(Stream s, int n)", "array": "Stream[]",
    "collection": "List<Stream>", "closure": "Action", "method_group": "Action",
    "nameof": "string", "member": "long",
}
# The handle's declared type, per shape (the others are MemoryStream).
HANDLE_TYPE = {"cast_checked": "Stream", "as_may_fail": "Stream", "boxing": "Token"}
EXPR = {
    "none": "r", "parens": "(r)", "bang": "r!", "cast_identity": "(MemoryStream)r",
    "cast_upcast": "(Stream)r", "as_upcast": "r as Stream", "cast_checked": "(MemoryStream)r",
    "as_may_fail": "r as MemoryStream", "cond": "flag ? r : q", "coalesce": "p ?? r",
    "switch": "k switch { 0 => r, _ => q }", "user_implicit": "r", "user_explicit": "(XBox)r",
    "boxing": "r", "nested": "Wrap(r)", "tuple": "(r, 1)", "array": "new Stream[] { r }",
    "collection": "new List<Stream> { r }", "closure": "() => Use(r)", "method_group": "r.Dispose",
    "nameof": "nameof(r)", "member": "r.Length",
}
# Shapes whose expression can stand as a receiver without parentheses.
BARE_RECEIVER = {"none", "bang", "nested", "array", "collection", "nameof", "member", "boxing",
                 "user_implicit"}


def feasible(s: str, w: str, b: str, c: str) -> bool:
    if b == "refout" and (w != "none" or s == "ext"):
        return False                     # `ref` needs a variable; a receiver is never `ref`
    if s == "ext" and b != "params" and w in {"user_implicit", "closure", "method_group"}:
        # no user-defined conversion on a receiver; a lambda / method group has no receiver type
        return False
    return True


def handle_kind(c: str) -> str:
    return "param" if c.endswith("_param") else "local"


def param_type(w: str, b: str) -> str:
    if b == "refout":
        return HANDLE_TYPE.get(w, "MemoryStream")
    return PARAM_TYPE.get(w, "Stream")


def receiver_expr(w: str) -> str:
    e = EXPR[w]
    return e if w in BARE_RECEIVER or w == "parens" else f"({e})"


def call_statement(s: str, w: str, b: str) -> str:
    e = EXPR[w]
    if s == "inv":
        return {"pos": f"Sink({e}, true);", "named": f"Sink(leaveOpen: true, s: {e});",
                "params": f"SinkP({e});", "refout": "SinkRef(ref r);", "default": f"SinkD({e});"}[b]
    if s == "ctor":
        return {"pos": f"new Sink2({e}, true);", "named": f"new Sink2(leaveOpen: true, s: {e});",
                "params": f"new SinkP2({e});", "refout": "new SinkRef2(ref r);",
                "default": f"new SinkD2({e});"}[b]
    if s == "del":
        return {"pos": f"take({e}, true);", "named": f"take(leaveOpen: true, s: {e});",
                "params": f"takeP({e});", "refout": "takeRef(ref r);", "default": f"takeD({e});"}[b]
    r = receiver_expr(w)
    return {"pos": f"{r}.Ext(true);", "named": f"{r}.Ext(leaveOpen: true);",
            "params": f"Stream.Null.ExtP({e});", "default": f"{r}.ExtD();"}[b]


def callee_decl(s: str, w: str, b: str) -> list[str]:
    t = param_type(w, b)
    if s == "inv":
        return {"pos": [f"static void Sink({t} s, bool leaveOpen) {{ }}"],
                "named": [f"static void Sink({t} s, bool leaveOpen) {{ }}"],
                "params": [f"static void SinkP(params {t}[] xs) {{ }}"],
                "refout": [f"static void SinkRef(ref {t} s) {{ }}"],
                "default": [f"static void SinkD({t} s, bool leaveOpen = true) {{ }}"]}[b]
    if s == "ctor":
        return {"pos": [f"sealed class Sink2 {{ public Sink2({t} s, bool leaveOpen) {{ }} }}"],
                "named": [f"sealed class Sink2 {{ public Sink2({t} s, bool leaveOpen) {{ }} }}"],
                "params": [f"sealed class SinkP2 {{ public SinkP2(params {t}[] xs) {{ }} }}"],
                "refout": [f"sealed class SinkRef2 {{ public SinkRef2(ref {t} s) {{ }} }}"],
                "default": [f"sealed class SinkD2 {{ public SinkD2({t} s, bool leaveOpen = true) "
                            "{ } }"]}[b]
    if s == "del":
        return {"pos": [f"delegate void Take({t} s, bool leaveOpen);"],
                "named": [f"delegate void Take({t} s, bool leaveOpen);"],
                "params": [f"delegate void TakeP(params {t}[] xs);"],
                "refout": [f"delegate void TakeRef(ref {t} s);"],
                "default": [f"delegate void TakeD({t} s, bool leaveOpen = true);"]}[b]
    # Private extension methods: every case shares one compilation and the global namespace,
    # and an inaccessible extension method is not a candidate for another case's receiver.
    return {"pos": [f"static void Ext(this {t} s, bool leaveOpen) {{ }}"],
            "named": [f"static void Ext(this {t} s, bool leaveOpen) {{ }}"],
            "params": [f"static void ExtP(this Stream s, params {t}[] xs) {{ }}"],
            "default": [f"static void ExtD(this {t} s, bool leaveOpen = true) {{ }}"]}[b]


def delegate_param(b: str) -> str:
    return {"pos": "Take take", "named": "Take take", "params": "TakeP takeP",
            "refout": "TakeRef takeRef", "default": "TakeD takeD"}[b]


def helpers(w: str) -> list[str]:
    out: list[str] = []
    if w == "user_implicit":
        out.append(BOX)
    if w == "user_explicit":
        out.append(XBOX)
    if w == "boxing":
        out.append("struct Token : IDisposable { public void Dispose() { } }")
    if w == "nested":
        out.append("static Stream Wrap(Stream s) { return s; }")
    if w == "closure":
        out.append("static void Use(Stream s) { }")
    return out


def pairwise_case(s: str, w: str, b: str, c: str) -> tuple[str, str, dict[str, Any]]:
    """One generated program plus its designed classification."""
    name = f"pw-{s}-{w}-{b}-{c}".replace("_", "-")
    cls = "H_" + name.replace("-", "_")
    h = handle_kind(c)
    ht = HANDLE_TYPE.get(w, "MemoryStream")
    params: list[str] = []
    body: list[str] = []
    if h == "param":
        params.append(f"{ht} r")
    else:
        init = "new Token()" if ht == "Token" else "new MemoryStream()"
        body.append(f"{'var' if ht == 'MemoryStream' or ht == 'Token' else ht} r = {init};")
    if w in {"cond", "switch"}:
        if h == "param":
            params.append("MemoryStream q")
        else:
            body.append("var q = new MemoryStream();")
    if w == "cond":
        params.append("bool flag")
    if w == "switch":
        params.append("int k")
    if w == "coalesce":
        body.append("MemoryStream? p = null;")
    if s == "del":
        params.append(delegate_param(b))
    if c == "record_local":
        body.append("var keep = new MemoryStream();")
    call = call_statement(s, w, b)
    if c.startswith("unmodelled"):
        body.append(f"lock (Gate) {{ {call} }}")
    else:
        body.append(call)
    if c == "orphan_local":
        # Every candidate must escape for the orphan gate: the handle and, where a may-value
        # form declares one, its alternative.
        body.append("Field = r;")
        if w in {"cond", "switch"}:
            body.append("Field = q;")
    if c == "record_local":
        body.append("keep.Dispose();")

    members: list[str] = []
    members += callee_decl(s, w, b)
    members += helpers(w)
    if c.startswith("unmodelled"):
        members.append("static readonly object Gate = new object();")
    if c == "orphan_local":
        members.append("static object Field;")
    src = "\n".join([
        HEADER,
        f"// composition: site={s} value_flow={w} binding={b} carrier={c}",
        "using System;",
        "using System.IO;",
        "using System.Collections.Generic;",
        "",
        f"static class {cls}",
        "{",
        *[f"    {m}" for m in members],
        f"    static void M({', '.join(params)})",
        "    {",
        *[f"        {line}" for line in body],
        "    }",
        "}",
        "",
    ])

    # ---- the designed classification, from the frozen taxonomy ----
    occurrences: list[dict[str, Any]] = []
    site_kind = {"inv": "invocation", "ext": "invocation", "ctor": "object_creation",
                 "del": "delegate_invocation"}[s]
    ordinal = 1 if (s == "ext" and b == "params") else 0
    if w in EXCLUSION:
        occ: dict[str, Any] = {"symbol": "r", "verdict": "excluded", "explanation": EXCLUSION[w],
                               "site_kind": site_kind, "ordinal": ordinal}
        if w == "closure":
            occ["nested_function"] = True
        occurrences.append(occ)
        relevant = False
    else:
        if b in {"params", "refout"} or w in MAY_VALUE:
            expected = "opaque"
        else:
            expected = "param" if h == "param" else "var"
        if w == "nested":
            inner = {"symbol": "r", "verdict": "captured", "site_kind": "invocation", "ordinal": 0,
                     "expected": "param" if h == "param" else "var",
                     "enclosing": [] if (s == "ext" and b != "params") else ["nested_call_result"]}
            occurrences.append(inner)
        else:
            occurrences.append({"symbol": "r", "verdict": "captured", "site_kind": site_kind,
                                "ordinal": ordinal, "expected": expected})
            if w in {"cond", "switch"}:
                occurrences.append({"symbol": "q", "verdict": "captured", "site_kind": site_kind,
                                    "ordinal": ordinal, "expected": "opaque"})
        relevant = True
    if c == "orphan_local":
        occurrences.append(exc("r", "storage_assignment"))
        if w in {"cond", "switch"}:
            occurrences.append(exc("q", "storage_assignment"))
    if c == "record_local":
        occurrences.append({"symbol": "keep", "verdict": "excluded",
                            "explanation": "receiver_not_summary_parameter"})
    if c.startswith("record"):
        carrier = "functions"
    else:
        carrier = "guarded_functions" if relevant else "none"
    design = {
        "member": f"{cls}.M",
        "composition": {"site": s, "value_flow": w, "binding": b, "carrier": c},
        "carrier": carrier,
        "occurrences": occurrences,
        "red": {},
    }
    # F-PARAMS-ELEMENT (an expanded params element classified from its bare syntax) was pinned
    # RED here until A2.2-4R2 repaired it: the design above is the truth for every binding.
    return name, src, design


def pairwise(feasible_tuples: Sequence[tuple[str, ...]]) -> list[tuple[str, ...]]:
    """Greedy pairwise covering: deterministic (first best in enumeration order)."""
    def pairs(t: tuple[str, ...]) -> set[tuple[tuple[int, str], tuple[int, str]]]:
        return {((i, t[i]), (j, t[j])) for i, j in itertools.combinations(range(len(t)), 2)}
    uncovered: set[tuple[tuple[int, str], tuple[int, str]]] = set()
    for t in feasible_tuples:
        uncovered |= pairs(t)
    chosen: list[tuple[str, ...]] = []
    while uncovered:
        best, best_n = None, 0
        for t in feasible_tuples:
            n = len(pairs(t) & uncovered)
            if n > best_n:
                best, best_n = t, n
        if best is None:
            break
        chosen.append(best)
        uncovered -= pairs(best)
    return chosen


# ---- the named cases: compositions, shadowing, member kinds, vocabulary edges ----

PRELUDE = ["using System;", "using System.IO;", "using System.Collections.Generic;", ""]


def named_case(name: str, why: str, members: list[str], design: dict[str, Any],
               member_lines: list[str] | None = None) -> tuple[str, str, dict[str, Any]]:
    cls = "H_" + name.replace("-", "_")
    src = "\n".join([
        HEADER,
        f"// {why}",
        *PRELUDE,
        f"static class {cls}",
        "{",
        *[f"    {m}" for m in members],
        "}",
        "",
    ])
    design = {"member": f"{cls}.M", **design, "why": why}
    return name, src, design


def cap(symbol: str, kind: str = "invocation", ordinal: int = 0, expected: str = "var",
        **extra: Any) -> dict[str, Any]:
    return {"symbol": symbol, "verdict": "captured", "site_kind": kind, "ordinal": ordinal,
            "expected": expected, **extra}


def exc(symbol: str, name: str, **extra: Any) -> dict[str, Any]:
    return {"symbol": symbol, "verdict": "excluded", "explanation": name, **extra}


def named_cases() -> list[tuple[str, str, dict[str, Any]]]:
    out: list[tuple[str, str, dict[str, Any]]] = []
    box, xbox = BOX, XBOX
    sink = "static void Sink(Stream s, bool leaveOpen) { }"
    # 1. parentheses + user conversion (implicit at the parameter, explicit behind a cast)
    out.append(named_case(
        "comp-parens-user-implicit",
        "composition: parentheses around a handle whose parameter type needs op_Implicit; the "
        "conversion wins over the transparent-looking syntax (§10.6.3)",
        [box, "static void TakeBox(Box b) { }",
         "static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); "
         "TakeBox((r)); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [exc("r", "user_conversion", site_kind="invocation", ordinal=0),
                         exc("keep", "receiver_not_summary_parameter")], "red": {}}))
    out.append(named_case(
        "comp-parens-user-explicit",
        "composition: parentheses around an explicit user-defined cast; the hidden call inside the "
        "cast expression is the edge that decides",
        [xbox, "static void TakeXBox(XBox b) { }",
         "static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); "
         "TakeXBox(((XBox)r)); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [exc("r", "user_conversion", site_kind="invocation", ordinal=0),
                         exc("keep", "receiver_not_summary_parameter")], "red": {}}))
    # 2. may-value arm + user conversion
    out.append(named_case(
        "comp-mayvalue-arm-user-conversion",
        "composition: a conditional whose whole value passes through op_Implicit at the parameter; "
        "an arm that reaches the callee only through a user-defined conversion is not a handle "
        "alternative (registry conversion_rules)",
        [box, "static void TakeBox(Box b) { }",
         "static void M(bool flag) { var r = new MemoryStream(); var q = new MemoryStream(); "
         "var keep = new MemoryStream(); TakeBox(flag ? r : q); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [exc("r", "user_conversion", site_kind="invocation", ordinal=0),
                         exc("q", "user_conversion", site_kind="invocation", ordinal=0),
                         exc("keep", "receiver_not_summary_parameter")], "red": {}}))
    out.append(named_case(
        "comp-mayvalue-arm-user-cast",
        "composition: one arm of a conditional is an explicit user-defined cast of the handle, the "
        "other arm is not a handle; the cast arm is excluded inside the may-value form",
        [xbox, "static void TakeXBox(XBox b) { }",
         "static void M(bool flag) { var r = new MemoryStream(); var other = new XBox(); "
         "var keep = new MemoryStream(); TakeXBox(flag ? (XBox)r : other); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [exc("r", "user_conversion", site_kind="invocation", ordinal=0),
                         exc("keep", "receiver_not_summary_parameter")], "red": {}}))
    # 3. named argument + transparent wrapper
    out.append(named_case(
        "comp-named-transparent",
        "composition: a named, reordered argument carrying a reference upcast; the declared "
        "ordinal is the parameter's, the fact is the unwrapped var",
        [sink, "static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); "
               "Sink(leaveOpen: true, s: (Stream)r); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [cap("r"), exc("keep", "receiver_not_summary_parameter")], "red": {}}))
    # 4. constructor + params
    out.append(named_case(
        "comp-ctor-params",
        "composition: a constructor whose parameter is a params array, expanded form; one opaque "
        "slot at the params ordinal, the call relevant, call_kind object_creation",
        ["sealed class SinkP2 { public SinkP2(params Stream[] xs) { } }",
         "static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); "
         "new SinkP2(r); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [cap("r", "object_creation", 0, "opaque"),
                         exc("keep", "receiver_not_summary_parameter")], "red": {}}))
    # 5. delegate + named argument
    out.append(named_case(
        "comp-delegate-named",
        "composition: a delegate invocation with named, reordered arguments; the delegate's "
        "declared parameter names resolve the binding, callee stays null",
        ["delegate void Take(Stream s, bool leaveOpen);",
         "static void M(Take take) { var r = new MemoryStream(); var keep = new MemoryStream(); "
         "take(leaveOpen: true, s: r); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [cap("r", "delegate_invocation", 0, "var"),
                         exc("keep", "receiver_not_summary_parameter")], "red": {}}))
    # 6. orphan method + direct flow
    out.append(named_case(
        "comp-orphan-direct",
        "composition: a direct flow into a non-consuming callee and nothing else tracked; the "
        "legacy pass reads the pass as an escape, the fact rides in the orphan carrier",
        ["static void Same(MemoryStream m) { }",
         "static void M() { var r = new MemoryStream(); Same(r); }"],
        {"carrier": "guarded_functions", "occurrences": [cap("r")], "red": {}}))
    # 7. nested call + transparent inner argument
    out.append(named_case(
        "comp-nested-transparent-inner",
        "composition: the inner call receives the handle through a reference upcast (captured "
        "there, unwrapped); the outer call receives the inner result (nested_call_result)",
        ["static Stream Wrap(Stream s) { return s; }", "static void Use(Stream s) { }",
         "static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); "
         "Use(Wrap((Stream)r)); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [cap("r", enclosing=["nested_call_result"]),
                         exc("keep", "receiver_not_summary_parameter")], "red": {}}))
    # 8. shadowing: same spelling, different symbols
    out.append(named_case(
        "shadow-sibling-scopes",
        "shadowing witness: two locals spelled `r` in sibling scopes; only the first is a "
        "candidate. A handle set keyed by spelling captured the second call too (F-SHADOW, "
        "repaired in A2.2-4R1: the sidecar binds by symbol)",
        [sink, "static void M() { { var r = new MemoryStream(); Sink(r, true); } "
               "{ Stream r = Stream.Null; Sink(r, true); } }"],
        {"carrier": "guarded_functions", "occurrences": [cap("r")], "red": {}}))
    out.append(named_case(
        "shadow-sibling-scopes-reversed",
        "shadowing witness: the non-candidate `r` comes first, the candidate second; order must "
        "not matter to a symbol-bound reading (F-SHADOW, repaired in A2.2-4R1)",
        [sink, "static void M() { { Stream r = Stream.Null; Sink(r, true); } "
               "{ var r = new MemoryStream(); Sink(r, true); } }"],
        {"carrier": "guarded_functions", "occurrences": [cap("r")], "red": {}}))
    out.append(named_case(
        "shadow-lambda-local",
        "shadowing witness: a handle created inside a lambda shares its spelling with a string "
        "local of the method; the string is not a candidate of anything, so no fact exists and "
        "no carrier holds the method (F-SHADOW, repaired in A2.2-4R1)",
        ["static void Run(Action a) { a(); }", "static void Use4(string s) { }",
         "static void M() { Run(() => { var r = new MemoryStream(); r.Dispose(); }); "
         "{ string r = \"x\"; Use4(r); } }"],
        {"carrier": "none", "occurrences": [], "red": {}}))
    out.append(named_case(
        "shadow-owner-form",
        "shadowing witness (the GO's literal form): `Stream r = ...; { Stream r2 = ...; "
        "Sink(r2); }`; the non-candidate r2 is captured by nobody and the candidate r is "
        "captured by symbol",
        [sink, "static void M() { Stream r = new MemoryStream(); "
               "{ Stream r2 = Stream.Null; Sink(r2, true); } Sink(r, true); }"],
        {"carrier": "guarded_functions", "occurrences": [cap("r")], "red": {}}))
    # member kinds the legacy pass never visits
    out.append(named_case(
        "member-expression-bodied",
        "member kind: an expression-bodied method with an owned parameter; the legacy pass visits "
        "block bodies only, so neither carrier sees the call (finding F-MEMBER)",
        [sink, "static void M(MemoryStream r) => Sink(r, true);"],
        {"carrier": "none", "occurrences": [cap("r", expected="param")],
         "red": {"occurrence_not_captured": 1}, "finding": "F-MEMBER"}))
    out.append(named_case(
        "member-struct",
        "member kind: a method of a struct; the legacy pass enumerates class declarations only "
        "(finding F-MEMBER)",
        [sink, "struct Holder { public void M(MemoryStream r) { Sink(r, true); } }"],
        {"member_override": ".Holder.M", "carrier": "none",
         "occurrences": [cap("r", expected="param")],
         "red": {"occurrence_not_captured": 1}, "finding": "F-MEMBER"}))
    out.append(named_case(
        "member-record",
        "member kind: a method of a record; the legacy pass enumerates class declarations only "
        "(finding F-MEMBER)",
        [sink, "sealed record Holder(int X) { public void M(MemoryStream r) { Sink(r, true); } }"],
        {"member_override": ".Holder.M", "carrier": "none",
         "occurrences": [cap("r", expected="param")],
         "red": {"occurrence_not_captured": 1}, "finding": "F-MEMBER"}))
    out.append(named_case(
        "member-accessor",
        "member kind: a property setter passing its `value` parameter; accessors are not "
        "BaseMethodDeclarationSyntax and are never visited (finding F-MEMBER)",
        [sink, "static MemoryStream Slot { set { Sink(value, true); } }"],
        {"member_override": ".set_Slot", "carrier": "none",
         "occurrences": [cap("value", expected="param")],
         "red": {"occurrence_not_captured": 1}, "finding": "F-MEMBER"}))
    out.append(named_case(
        "member-local-function",
        "member kind: the call sits in a declared local function; the capture is a named non-call "
        "context of the method and the inner call is the known unobserved gap, counted, not RED",
        [sink, "static void M() { var r = new MemoryStream(); void L() { Sink(r, true); } L(); }"],
        {"carrier": "none",
         "occurrences": [{"symbol": "r", "verdict": "not_call_related",
                          "explanation": "local_function_declaration", "nested_function": True}],
         "red": {}}))
    out.append(named_case(
        "ext-conditional-access",
        "site form: a reduced extension method invoked through `?.` on the handle; the receiver "
        "still binds declared ordinal 0 (F-CONDITIONAL-RECEIVER, repaired in A2.2-4R3)",
        ["static void Ext(this Stream s, bool leaveOpen) { }",
         "static void M() { MemoryStream? r = new MemoryStream(); var keep = new MemoryStream(); "
         "r?.Ext(true); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [cap("r"), exc("keep", "receiver_not_summary_parameter")],
         "red": {}}))
    out.append(named_case(
        "ext-boxed-receiver",
        "site form: a struct handle as the receiver of an extension method on object; the receiver "
        "conversion is boxing, so nothing of the handle reaches ordinal 0",
        ["struct Token : IDisposable { public void Dispose() { } }",
         "static void ExtObj(this object o, bool leaveOpen) { }",
         "static void M(Token r) { r.ExtObj(true); }"],
        {"carrier": "functions",
         "occurrences": [exc("r", "boxing_conversion", site_kind="invocation", ordinal=0)],
         "red": {}}))
    # argument shapes the frozen vocabulary has no name for
    out.append(named_case(
        "vocab-tested-operand",
        "vocabulary edge: the handle is compared and the boolean is the argument; no frozen "
        "exclusion names a tested operand under an argument (finding F-VOCAB)",
        ["static void Log(bool b) { }",
         "static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); "
         "Log(r != null); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [{"symbol": "r", "verdict": "red",
                          "explanation": "unclassified_argument_shape:tested_operand"},
                         exc("keep", "receiver_not_summary_parameter")],
         "red": {"unclassified_argument_shape:tested_operand": 1}, "finding": "F-VOCAB"}))
    out.append(named_case(
        "vocab-interpolation-hole",
        "vocabulary edge: the handle is an interpolation hole and the string is the argument "
        "(finding F-VOCAB)",
        ["static void Log(string s) { }",
         "static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); "
         "Log($\"{r}\"); keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [{"symbol": "r", "verdict": "red",
                          "explanation": "unclassified_argument_shape:interpolation_hole"},
                         exc("keep", "receiver_not_summary_parameter")],
         "red": {"unclassified_argument_shape:interpolation_hole": 1}, "finding": "F-VOCAB"}))
    out.append(named_case(
        "vocab-indexer-argument",
        "vocabulary edge: the handle is the index of an element access (finding F-VOCAB)",
        ["static void M() { var r = new MemoryStream(); var keep = new MemoryStream(); "
         "var d = new Dictionary<Stream, int>(); d[r] = 1; keep.Dispose(); }"],
        {"carrier": "functions",
         "occurrences": [{"symbol": "r", "verdict": "red",
                          "explanation": "unclassified_argument_shape:indexer_argument"},
                         exc("keep", "receiver_not_summary_parameter")],
         "red": {"unclassified_argument_shape:indexer_argument": 1}, "finding": "F-VOCAB"}))
    out.append(named_case(
        "vocab-constructor-initializer",
        "vocabulary edge: an owned constructor parameter forwarded through `: base(...)`, a call "
        "site that is neither an invocation nor an object creation (finding F-VOCAB)",
        ["class Base { public Base(MemoryStream r, bool b) { } }",
         "sealed class Holder : Base { public Holder(MemoryStream r) : base(r, true) { } }"],
        {"member_override": ".Holder..ctor", "carrier": "none",
         "occurrences": [{"symbol": "r", "verdict": "red",
                          "explanation": "unclassified_argument_shape:constructor_initializer"}],
         "red": {"unclassified_argument_shape:constructor_initializer": 1}, "finding": "F-VOCAB"}))
    return out


def generate_all() -> tuple[dict[str, str], dict[str, Any]]:
    tuples = [t for t in itertools.product(SITES, WRAPPERS, BINDINGS, CARRIERS) if feasible(*t)]
    chosen = pairwise(tuples)
    sources: dict[str, str] = {}
    cases: dict[str, Any] = {}
    for t in chosen:
        name, src, design = pairwise_case(*t)
        sources[name] = src
        cases[name] = design
    for name, src, design in named_cases():
        sources[name] = src
        cases[name] = design
    factor_names = ["site", "value_flow", "binding", "carrier"]
    expected = {
        "schema": SCHEMA,
        "generator": "scripts/p037_hostile_census.py",
        "why": ("Designed classifications for the completeness oracle "
                "(frontend/roslyn/OwnSharp.Oracle): each case's method lists its universe "
                "occurrences with the verdict the frozen taxonomy assigns, the carrier "
                "production must deliver, and, for a case that witnesses a classified finding, "
                "the exact RED the oracle must raise. Written by the generator from the design, "
                "never recorded from a run."),
        "factors": {"site": SITES, "value_flow": WRAPPERS, "binding": BINDINGS,
                    "carrier": CARRIERS},
        "pairwise": {"feasible_tuples": len(tuples), "cases": len(chosen),
                     "factor_pairs": [f"{factor_names[a]} x {factor_names[b]}"
                                      for a, b in itertools.combinations(range(4), 2)]},
        "cases": dict(sorted(cases.items())),
    }
    return sources, expected


def write(sources: dict[str, str], expected: dict[str, Any], root: Path) -> None:
    cases = root / "cases"
    cases.mkdir(parents=True, exist_ok=True)
    for old in cases.glob("*.cs"):
        if old.stem not in sources:
            old.unlink()
    for name, src in sources.items():
        (cases / f"{name}.cs").write_text(src, encoding="utf-8")
    (root / "expected.json").write_text(json.dumps(expected, indent=1) + "\n", encoding="utf-8")


def check() -> int:
    sources, expected = generate_all()
    with tempfile.TemporaryDirectory(prefix="p037-hostile-") as td:
        write(sources, expected, Path(td))
        fresh = Path(td)
        problems: list[str] = []
        committed = {p.name for p in CASES.glob("*.cs")} if CASES.exists() else set()
        generated = {p.name for p in (fresh / "cases").glob("*.cs")}
        for n in sorted(committed - generated):
            problems.append(f"stale committed case {n}")
        for n in sorted(generated - committed):
            problems.append(f"missing committed case {n}")
        for n in sorted(generated & committed):
            if (CASES / n).read_bytes() != (fresh / "cases" / n).read_bytes():
                problems.append(f"case {n} differs from a regeneration")
        if not EXPECTED.exists() or EXPECTED.read_bytes() != (fresh / "expected.json").read_bytes():
            problems.append("expected.json differs from a regeneration")
    for p in problems:
        print(f"FAIL[hostile-census-drift]: {p}")
    if problems:
        return 1
    n_pairwise = expected["pairwise"]["cases"]
    print(f"ok[hostile-census-drift]: {len(sources)} case(s) equal a regeneration "
          f"({n_pairwise} pairwise + {len(sources) - n_pairwise} named)")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cmd", choices=("generate", "check"))
    args = ap.parse_args(argv)
    if args.cmd == "generate":
        sources, expected = generate_all()
        write(sources, expected, OUT)
        print(f"generated {len(sources)} case(s) into {OUT.relative_to(ROOT)}")
        return 0
    return check()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
