#!/usr/bin/env python3
"""Render the P-022 checkpoint status fragments from the evidence in the tree.

The status surfaces (the P-022 table, the proposals index, a checkpoint note)
say WHAT a checkpoint proves and link here; the measured numbers live only in
these generated fragments, computed from the evidence — never typed:

* `docs/generated/p022-cp4-census.md` — the verdict ledger census, from
  `tests/verdict_census.compute_verdict_census()` (the same interpretation the
  fixture harness uses).
* `docs/generated/p022-cp4-mutations.md` — the recorded mutation campaign,
  from `docs/evidence/p022-cp4-mutations.json` and its `.result.json`, through
  `scripts/mutate_campaign.summarize()` (the same interpretation the runner
  prints).

Determinism: nothing in a fragment depends on HEAD, the clock or the
environment, so an unrelated commit never changes one. The campaign fragment
carries the campaign's own provenance (the commit the run was taken on)
because that is data from the recorded run, not a property of the tree.

Usage:
  python scripts/render_checkpoint_status.py            # (re)write the fragments
  python scripts/render_checkpoint_status.py --check    # exit 1 when a committed fragment
                                                        # differs from the projection
`tests/test_checkpoint_status.py` runs `--check` in-process inside
`tests/run_tests.py`, so a change to the evidence without regenerating the
fragments turns the existing Python gate red.
"""

from __future__ import annotations

import difflib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for _sub in ("tests", "scripts"):
    _p = os.path.join(ROOT, _sub)
    if _p not in sys.path:
        sys.path.insert(0, _p)

from mutate_campaign import (  # noqa: E402  (sys.path set above)
    CampaignError,
    Definition,
    Result,
    Summary,
    load_definition,
    load_result,
    summarize,
)
from verdict_census import Census, CensusError, compute_verdict_census  # noqa: E402

GENERATED = os.path.join(ROOT, "docs", "generated")
CENSUS_MD = "p022-cp4-census.md"
MUTATIONS_MD = "p022-cp4-mutations.md"
CAMPAIGN = os.path.join(ROOT, "docs", "evidence", "p022-cp4-mutations.json")
RESULT = os.path.join(ROOT, "docs", "evidence", "p022-cp4-mutations.result.json")
SELF = "scripts/render_checkpoint_status.py"


def _header(sources: str) -> str:
    return (f"<!-- GENERATED by {SELF} from {sources}. Do not edit: regenerate with "
            f"`python {SELF}`; tests/run_tests.py fails while this file is stale. -->\n")


def _rel(path: str) -> str:
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


# --- census ---------------------------------------------------------------


def render_census(c: Census) -> str:
    rows: list[tuple[str, str]] = [
        ("goldens — Python's complete truth, one per planned case", str(c.goldens))]
    for origin, n in c.by_origin:
        label = ("synthetic controls (`manifest.json` cases)" if origin == "synthetic"
                 else f"swept from `tests/fixtures/{origin}`")
        rows.append((f"… {label}", str(n)))
    rows += [
        ("reference refusals over all goldens", str(c.python_refusals)),
        ("reference findings over all goldens", str(c.python_findings)),
        ("declared Rust exclusions — the executable ledger `rust_replay_excluded`",
         str(c.excluded)),
    ]
    for refusal, contains, n in c.excluded_by_expectation:
        if refusal == "door":
            what = "… refused at the typed `OwnIr` door (#294 OD-1)"
        else:
            what = f"… refused by `check_facts` with an error containing `{contains}`"
        rows.append((what, str(n)))
    rows += [
        ("replayed by Rust at the cp4 surface (goldens minus exclusions)", str(c.replayed)),
        ("… reference refusals among them (compared by refusal class)",
         str(c.replayed_refusals)),
        ("… findings among them (compared on the cp4 members)", str(c.replayed_findings)),
    ]
    width = max(len(k) for k, _ in rows)
    lines = [
        _header("tests/fixtures/verdicts/manifest.json and the *.verdicts.json goldens"),
        "# P-022 checkpoint 4 — measured census",
        "",
        "Computed by `tests/verdict_census.py` (the interpretation "
        "`tests/test_verdict_fixtures.py` verifies against the Python projection) over the "
        "frozen Layer 3 ledger; the Rust half is `rust/crates/own-bridge/tests/verdicts.rs`.",
        "",
        f"| {'measure'.ljust(width)} | value |",
        f"|{'-' * (width + 2)}|------:|",
    ]
    lines += [f"| {k.ljust(width)} | {v} |" for k, v in rows]
    lines += [
        "",
        "The differential counts over the replayed set — Python-only, Rust-only, changed, "
        "ordering-only, unexplained — are asserted, not measured here: the Rust replay "
        "compares every replayed case's full ordered verdict list (or its refusal class) "
        "against the golden on the cp4 members, collects every divergence without "
        "fail-fast, and fails if one exists. A green "
        "`cargo test -p own-bridge --test verdicts` is 0 / 0 / 0 / 0 / 0 by construction; "
        "a non-zero count is a red build.",
        "",
    ]
    return "\n".join(lines)


# --- mutation campaign ----------------------------------------------------


def _load_campaign() -> tuple[Definition | None, Result | None, list[str]]:
    problems: list[str] = []
    definition: Definition | None = None
    result: Result | None = None
    if os.path.exists(CAMPAIGN):
        try:
            definition = load_definition(CAMPAIGN)
        except (CampaignError, OSError, ValueError) as e:
            problems.append(f"campaign definition unreadable: {e}")
    if definition is not None and os.path.exists(RESULT):
        try:
            result = load_result(RESULT)
        except (CampaignError, OSError, ValueError) as e:
            problems.append(f"campaign result unreadable: {e}")
    return definition, result, problems


def render_mutations(definition: Definition | None, result: Result | None,
                     summary: Summary | None) -> str:
    lines = [_header(f"{_rel(CAMPAIGN)} and {_rel(RESULT)}"),
             "# P-022 checkpoint 4 — mutation campaign", ""]
    if definition is None:
        lines += ["No campaign definition is committed (expected at "
                  f"`{_rel(CAMPAIGN)}`).", ""]
        return "\n".join(lines)
    lines += [
        f"Campaign `{definition.campaign}` — {definition.description}",
        "",
        f"Definition: `{_rel(CAMPAIGN)}` (sha256 `{definition.sha256[:16]}…`, "
        f"{len(definition.mutations)} mutations). Replay on a clean tree with "
        f"`python scripts/mutate_campaign.py --campaign {_rel(CAMPAIGN)} --run`; the "
        "recorded run is raw outcomes and provenance, the counts below are derived from it.",
        "",
    ]
    if result is None or summary is None:
        lines += [f"**No recorded run** is committed (expected at `{_rel(RESULT)}`): the "
                  "campaign has a definition but no evidence. Nothing below is a number.", ""]
        return "\n".join(lines)
    rows: list[tuple[str, str]] = [
        ("recorded at commit", f"`{summary.source_commit}`"),
        ("packages tested (every workspace member, `--no-fail-fast`)",
         ", ".join(f"`{p}`" for p in result.packages)),
        ("mutations", str(summary.total)),
        ("caught", str(summary.caught)),
        ("survived", str(summary.survived)),
        ("compile-error (no evidence either way)", str(summary.compile_error)),
        ("invalid-mutation", str(summary.invalid)),
        ("runner-error", str(summary.runner_error)),
        ("caught without every expected catcher",
         ", ".join(summary.expected_catchers_missed) or "none"),
        (f"honesty control `{definition.control_id}` (unmutated tree must pass)",
         f"{result.control.outcome}" + (" — as required" if summary.control_ok else " — VOID")),
    ]
    width = max(len(k) for k, _ in rows)
    lines += [f"| {'measure'.ljust(width)} | value |", f"|{'-' * (width + 2)}|---|"]
    lines += [f"| {k.ljust(width)} | {v} |" for k, v in rows]
    if summary.problems:
        lines += ["", "**This run is not evidence:**", ""]
        lines += [f"- {p}" for p in summary.problems]
    lines += ["", "| id | rule | mutation | outcome | caught by |", "|---|---|---|---|---|"]
    recorded = {o.id: o for o in result.mutations}
    for m in definition.mutations:
        o = recorded.get(m.id)
        if o is None:
            outcome, by = "**not recorded**", "—"
        else:
            outcome = o.outcome
            if o.expected_catchers_hit is False:
                outcome += " (expected catchers missed)"
            by = "<br>".join(f"`{c}`" for c in o.catchers) or (o.detail or "—")
        lines.append(f"| {m.id} | {m.rule or '—'} | {m.description} | {outcome} | {by} |")
    lines.append("")
    return "\n".join(lines)


# --- fragments ------------------------------------------------------------


def fragments() -> tuple[dict[str, str], list[str]]:
    """name -> rendered content, plus the problems that make a fragment
    non-evidence (a broken ledger, a campaign result that does not match its
    definition, a run over a dirty tree)."""
    out: dict[str, str] = {}
    problems: list[str] = []
    try:
        out[CENSUS_MD] = render_census(compute_verdict_census())
    except CensusError as e:
        problems.extend(f"verdict census: {p}" for p in e.problems)
    definition, result, campaign_problems = _load_campaign()
    problems.extend(campaign_problems)
    summary = summarize(definition, result) if definition and result else None
    if summary is not None:
        problems.extend(f"mutation campaign: {p}" for p in summary.problems)
    out[MUTATIONS_MD] = render_mutations(definition, result, summary)
    return out, problems


def check() -> list[str]:
    """Every committed fragment must equal its projection, byte for byte."""
    rendered, problems = fragments()
    for name, want in rendered.items():
        path = os.path.join(GENERATED, name)
        if not os.path.exists(path):
            problems.append(f"{_rel(path)}: missing — run `python {SELF}`")
            continue
        with open(path, encoding="utf-8") as f:
            have = f.read()
        if have != want:
            diff = "".join(difflib.unified_diff(
                have.splitlines(keepends=True), want.splitlines(keepends=True),
                fromfile=f"{_rel(path)} (committed)", tofile=f"{_rel(path)} (projection)", n=1))
            problems.append(f"{_rel(path)}: stale — the evidence changed without "
                            f"regenerating it (run `python {SELF}`):\n{diff}")
    return problems


def write() -> list[str]:
    rendered, problems = fragments()
    os.makedirs(GENERATED, exist_ok=True)
    for name, content in rendered.items():
        path = os.path.join(GENERATED, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"wrote {_rel(path)}")
    return problems


def main(argv: list[str]) -> int:
    if argv and argv != ["--check"]:
        print(__doc__)
        return 2
    problems = check() if argv else write()
    for p in problems:
        print(f"FAIL: checkpoint status {p}")
    if problems:
        return 1
    if argv:
        print(f"checkpoint status fragments OK: {CENSUS_MD}, {MUTATIONS_MD} "
              f"in sync with the evidence")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
