// The synthetic second extension's generator (OX-02 live gate). It adds ONE fixed source: a
// turnstile state protocol in the shape Own.NET's state-protocol lowering reads (a
// [ProtocolRegion] entry handing a [ProtocolToken] ref struct to a callback; every token
// method a transition). The attributes are matched by name, so they are declared here, in
// this extension's own namespace.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Owen.TestProtocol
{
    [Generator(LanguageNames.CSharp)]
    public sealed class TurnstileGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context) =>
            context.RegisterPostInitializationOutput(static post =>
                post.AddSource("Turnstile.Protocol.g.cs", SourceText.From(Source, Encoding.UTF8)));

        private const string Source = @"// Generated by Owen.TestProtocol (a synthetic test extension).
#nullable enable
using System;

namespace Owen.TestProtocol
{
    [AttributeUsage(AttributeTargets.Struct)]
    internal sealed class ProtocolTokenAttribute : Attribute { }

    [AttributeUsage(AttributeTargets.Method)]
    internal sealed class ProtocolRegionAttribute : Attribute { }

    public enum TurnstileState { Locked, Unlocked }

    public sealed class Turnstile
    {
        public TurnstileState State { get; internal set; }
    }

    [ProtocolToken]
    public readonly ref struct LockedTurnstile
    {
        private readonly Turnstile _turnstile;
        internal LockedTurnstile(Turnstile turnstile) => _turnstile = turnstile;

        public UnlockedTurnstile Coin()
        {
            _turnstile.State = TurnstileState.Unlocked;
            return new UnlockedTurnstile(_turnstile);
        }
    }

    [ProtocolToken]
    public readonly ref struct UnlockedTurnstile
    {
        private readonly Turnstile _turnstile;
        internal UnlockedTurnstile(Turnstile turnstile) => _turnstile = turnstile;

        public void Push() => _turnstile.State = TurnstileState.Locked;
    }

    public delegate void LockedRegion(LockedTurnstile locked);

    public static class TurnstileProtocol
    {
        [ProtocolRegion]
        public static void WithLocked(Turnstile turnstile, LockedRegion body)
        {
            if (turnstile.State != TurnstileState.Locked)
                throw new InvalidOperationException(""the turnstile is not locked"");
            body(new LockedTurnstile(turnstile));
        }
    }
}
";
    }
}
